### ISSUE TITLE
Geen plugin

### ISSUE THREAD

**Issue by Theo-denBlanken** [RickVellinga/Held#2]
aangetroffen

**Comment by RickVellinga** [comment]
Er zit nu een Heading gradiënt plugin in.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Theo den Blanken <notifications@github.com>
Verzonden: Monday, March 9, 2020 12:17:52 PM
Aan: RickVellinga/Held <Held@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [RickVellinga/Held] Geen plugin (#2)


aangetroffen

**Comment by RickVellinga** [comment]
Nu wel
